import { notFound } from 'next/navigation';
import Link from 'next/link';
import { getProduct,productInclude,productCard } from '@/lib/products';
import { db } from '@/lib/db';
import { ProductDetails } from '@/components/product-details';
import { ProductGrid } from '@/components/product-grid';
import { ReviewCarousel } from '@/components/review-carousel';
import { priceFor,inStock } from '@/lib/pricing';
import { metadataFor,StructuredData,siteUrl } from '@/lib/seo';
type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props){const p=await getProduct((await params).slug);return p?metadataFor(p,'/product/'+p.slug):{};}
export default async function ProductPage({params}:Props){const p=await getProduct((await params).slug);if(!p)notFound();const related=await db.product.findMany({where:{id:{not:p.id},status:'PUBLISHED',categories:{some:{categoryId:{in:p.categories.map(c=>c.categoryId)}}}},include:productInclude,take:4});const price=priceFor(p);const stock=p.productType==='VARIABLE'?p.variants.some(v=>v.active&&inStock(v.inventory)):inStock(p.inventory);const reviewStats=await db.review.aggregate({where:{productId:p.id,approved:true},_avg:{rating:true},_count:true});return <div className="container-shell py-10"><StructuredData value={{'@context':'https://schema.org','@type':'Product',name:p.name,sku:p.sku,brand:{'@type':'Brand',name:'Zalmi'},image:p.images.map(i=>new URL(i.url,siteUrl()).href),description:p.shortDescription,offers:{'@type':'Offer',priceCurrency:'PKR',price:price.current/100,availability:'https://schema.org/'+(stock?'InStock':'OutOfStock'),url:siteUrl()+'/product/'+p.slug,seller:{'@type':'Organization',name:'Zalmi'}},...(reviewStats._count?{aggregateRating:{'@type':'AggregateRating',ratingValue:reviewStats._avg.rating,reviewCount:reviewStats._count}}:{})}}/><nav className="text-sm text-muted"><Link href="/">Home</Link> / <Link href="/shop">Shop</Link> / {p.name}</nav><ProductDetails product={{...p,saleStart:p.saleStart?.toISOString(),saleEnd:p.saleEnd?.toISOString()}}/><div className="grid gap-8 border-t py-10 md:grid-cols-2"><section><h2 className="mb-4 text-xl font-bold">Description</h2><p className="whitespace-pre-line text-sm leading-7 text-muted">{p.description}</p>{p.care&&<><h3 className="mb-3 mt-6 font-bold">Care instructions</h3><p className="whitespace-pre-line text-sm leading-7">{p.care}</p></>}</section><section><h2 className="mb-4 text-xl font-bold">Specifications</h2><dl>{[['Material',p.material],['Sole',p.soleType],['Style',p.style],['Gender',p.gender],['Dimensions',p.dimensions],['Weight',p.weight?`${p.weight} kg`:'']].filter(([,v])=>v).map(([k,v])=><div key={k} className="flex justify-between border-b py-3 text-sm"><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section></div>{p.reviews.length>0&&<section className="py-8"><h2 className="text-xl font-bold">Customer reviews</h2><ReviewCarousel reviews={p.reviews}/></section>}<section className="py-8"><h2 className="mb-6 text-xl font-bold">You may also like</h2><ProductGrid products={related.map(productCard)}/></section></div>;}
