import Link from 'next/link';
import { listProducts } from '@/lib/products';
import { getCategories } from '@/lib/categories';
import { db } from '@/lib/db';
import { ProductGrid } from './product-grid';
export async function CatalogListing({params,categoryId}:{params:Record<string,string|undefined>;categoryId?:string}){
 const [result,categories,options]=await Promise.all([listProducts(params,categoryId),getCategories(),db.productVariant.findMany({where:{active:true,product:{status:'PUBLISHED'}},select:{size:true,color:true},distinct:['size','color'],take:200})]);
 const link=(page:number)=>'?'+new URLSearchParams({...Object.fromEntries(Object.entries(params).filter((v):v is [string,string]=>typeof v[1]==='string')),page:String(page)}).toString();
 return <><form className="my-8 grid gap-3 rounded border bg-surface-muted p-4 sm:grid-cols-2 lg:grid-cols-4"><input name="q" placeholder="Search products" aria-label="Search products" defaultValue={params.q}/>{!categoryId&&<select name="category" aria-label="Category" defaultValue={params.category}><option value="">All categories</option>{categories.map(c=><option key={c.id} value={c.slug}>{c.name}</option>)}</select>}<input type="number" min="0" name="min" placeholder="Minimum price (PKR)" aria-label="Minimum price" defaultValue={params.min}/><input type="number" min="0" name="max" placeholder="Maximum price (PKR)" aria-label="Maximum price" defaultValue={params.max}/><select name="size" aria-label="Size" defaultValue={params.size}><option value="">All sizes</option>{[...new Set(options.map(o=>o.size))].filter(Boolean).sort().map(v=><option key={v}>{v}</option>)}</select><select name="color" aria-label="Color" defaultValue={params.color}><option value="">All colors</option>{[...new Set(options.map(o=>o.color))].filter(Boolean).sort().map(v=><option key={v}>{v}</option>)}</select><select name="availability" aria-label="Availability" defaultValue={params.availability}><option value="">All availability</option><option value="in-stock">In stock</option></select><select name="sort" aria-label="Sort" defaultValue={params.sort||'newest'}><option value="newest">Newest</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="featured">Featured</option></select><button className="bg-brand px-4 py-2 font-semibold">Apply filters</button></form><p className="mb-4 text-sm text-muted">{result.total} products</p><ProductGrid products={result.products}/><nav aria-label="Pagination" className="mt-8 flex items-center justify-center gap-5">{result.page>1&&<Link href={link(result.page-1)}>Previous</Link>}<span>Page {result.page} of {Math.max(1,result.pages)}</span>{result.page<result.pages&&<Link href={link(result.page+1)}>Next</Link>}</nav></>;
}
