"use client";
import Image from 'next/image';
import Link from 'next/link';
import { Menu,Search,ShoppingBag,User } from 'lucide-react';
import { useState } from 'react';
import { StoreNavigation } from './store-navigation';
import { useCart } from './cart-provider';
import type { StoreSettings } from '@/lib/validation';
import type { MenuItem } from '@/lib/navigation-types';
export function Header({settings,items}:{settings:StoreSettings;items:MenuItem[]}){
 const [mobileOpen,setMobileOpen]=useState(false);const [searchOpen,setSearchOpen]=useState(false);const {items:cart}=useCart();
 return <header className="sticky top-0 z-40 bg-surface shadow-[0_1px_0_rgba(0,0,0,0.04)]"><div className="container-shell flex h-[72px] items-center justify-between gap-4"><div className="flex items-center gap-4"><button type="button" className="inline-flex h-9 w-9 items-center justify-center rounded-[3px] border border-border lg:hidden" aria-label="Open menu" onClick={()=>setMobileOpen(true)}><Menu className="h-4 w-4"/></button><Link href="/" aria-label={settings.storeName+' home'}><Image src={settings.logo} alt={settings.storeName} width={150} height={50} className="h-auto w-[120px] sm:w-[150px]"/></Link></div><nav aria-label="Main navigation" className="hidden flex-1 justify-center lg:flex"><StoreNavigation items={items}/></nav><div className="flex items-center gap-2 sm:gap-3"><button className="flex h-9 w-9 items-center justify-center rounded-[3px] border border-border" aria-label="Search" aria-expanded={searchOpen} onClick={()=>setSearchOpen(!searchOpen)}><Search className="h-4 w-4"/></button><Link href="/admin" className="hidden h-9 w-9 items-center justify-center rounded-[3px] border border-border sm:flex" aria-label="Store administration"><User className="h-4 w-4"/></Link><Link href="/cart" className="relative flex h-9 w-9 items-center justify-center rounded-[3px] border border-border" aria-label="Cart"><ShoppingBag className="h-4 w-4"/><span className="absolute -right-1 -top-1 flex h-4 min-w-4 items-center justify-center rounded-full bg-brand px-1 text-[9px] font-bold">{cart.reduce((n,i)=>n+i.quantity,0)}</span></Link></div></div>{searchOpen&&<form action="/shop" className="container-shell flex gap-2 pb-4"><input name="q" aria-label="Search products" placeholder="Search products" className="flex-1 border p-2"/><button className="bg-brand px-4">Search</button></form>}{mobileOpen&&<div className="fixed inset-0 z-50" role="dialog" aria-modal="true" aria-label="Navigation"><button className="absolute inset-0 bg-black/25" aria-label="Close menu" onClick={()=>setMobileOpen(false)}/><aside className="absolute left-0 top-0 h-full w-[86%] max-w-sm overflow-y-auto bg-surface p-5 shadow-lg"><div className="mb-6 flex justify-between"><span className="text-xl font-black uppercase">{settings.storeName}</span><button aria-label="Close menu" onClick={()=>setMobileOpen(false)}>×</button></div><nav><StoreNavigation items={items} mobile onNavigate={()=>setMobileOpen(false)}/></nav></aside></div>}</header>;
}
