"use client";
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import { useCart } from './cart-provider';
import { priceFor,money,inStock,type PriceInput } from '@/lib/pricing';
type Stock={available:boolean;quantity:number;allowBackorders:boolean};
export type DetailProduct=PriceInput&{id:string;name:string;sku:string;shortDescription:string;images:{url:string;alt:string}[];inventory:Stock|null;productType:string;variants:{id:string;sku:string;size:string;color:string;regularPrice:number|null;salePrice:number|null;image:string;active:boolean;inventory:Stock|null}[]};
export function ProductDetails({product}:{product:DetailProduct}){
 const variants=product.variants.filter(v=>v.active);const [variantId,setVariantId]=useState('');const [quantity,setQuantity]=useState(1);const [gallery,setGallery]=useState(0);const [added,setAdded]=useState(false);const cart=useCart();const variant=variants.find(v=>v.id===variantId);const price=priceFor(product,variant);const stock=variant?.inventory??product.inventory;const available=(product.productType==='SIMPLE'||!!variant)&&inStock(stock,quantity);const photo=variant?.image||product.images[gallery]?.url;
 return <div className="grid gap-10 py-8 lg:grid-cols-2"><div><div className="relative aspect-square overflow-hidden rounded border bg-surface-muted">{photo&&<Image src={photo} alt={product.images[gallery]?.alt||product.name} fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-contain" preload/>}</div><div className="mt-3 flex gap-3 overflow-auto">{product.images.map((image,i)=><button key={image.url+i} aria-label={'View image '+(i+1)} className={'relative h-20 w-20 shrink-0 border '+(i===gallery?'border-black':'border-border')} onClick={()=>{setGallery(i);setVariantId('');}}><Image src={image.url} alt={image.alt||product.name} fill sizes="80px" className="object-cover"/></button>)}</div></div><div><p className="text-xs uppercase tracking-widest text-muted">{variant?.sku||product.sku}</p><h1 className="mt-3 text-3xl font-bold tracking-tight">{product.name}</h1><div className="my-5 flex items-center gap-3">{price.current<price.regular&&<del className="text-muted">{money(price.regular)}</del>}<strong className="text-2xl">{money(price.current)}</strong>{price.percentage>0&&<span className="bg-brand px-2 py-1 text-xs">Save {price.percentage}%</span>}</div><p className="text-sm leading-7 text-muted">{product.shortDescription}</p>{product.productType==='VARIABLE'&&<label className="mt-6 block text-sm font-semibold">Size / Color<select className="mt-2 block w-full border p-3" value={variantId} onChange={e=>{setVariantId(e.target.value);setAdded(false);}}><option value="">Choose an option</option>{variants.map(v=><option key={v.id} value={v.id} disabled={!inStock(v.inventory)}>{[v.size,v.color].filter(Boolean).join(' / ')}{!inStock(v.inventory)?' — Out of Stock':''}</option>)}</select></label>}<p className="mt-4 text-sm" role="status">{product.productType==='VARIABLE'&&!variant?'Select size and color':inStock(stock)?stock!.allowBackorders&&stock!.quantity<=0?'Available on backorder':`${stock!.quantity} in stock`:'Out of Stock'}</p><div className="mt-5 flex gap-3"><label className="text-sm">Quantity<input type="number" min="1" max="99" value={quantity} onChange={e=>setQuantity(Math.max(1,Math.min(99,Number(e.target.value)||1)))} className="mt-1 block w-20 border p-3"/></label><button disabled={!available} className="mt-6 flex-1 bg-brand px-6 py-3 text-sm font-bold uppercase disabled:cursor-not-allowed disabled:opacity-40" onClick={()=>{cart.add({productId:product.id,variantId:variant?.id||null,quantity,name:product.name,image:photo||'',price:price.current,options:variant?[variant.size,variant.color].join(' / '):''});setAdded(true);}}>Add to Cart</button></div>{added&&<p className="mt-4" role="status">Added to your cart. <Link href="/cart" className="underline">View cart</Link></p>}</div></div>;
}
