export type Field={key:string;label:string;type?:'text'|'textarea'|'number'|'money'|'boolean'|'select'|'date'|'media'|'json'|'categories'|'password';options?:string[];section?:string;hint?:string;nullable?:boolean};
export type Resource={label:string;fields:Field[];defaults:Record<string,unknown>;search:string[];readOnly?:boolean};
const seo:Field[]=['seoTitle','metaDescription','canonicalUrl','ogTitle','ogDescription','ogImage','noindex'].map(key=>({key,label:key.replace(/([A-Z])/g,' $1'),section:'SEO',type:key==='noindex'?'boolean':key==='ogImage'?'media':key==='metaDescription'?'textarea':'text'}));
const seoDefaults={seoTitle:'',metaDescription:'',canonicalUrl:'',ogTitle:'',ogDescription:'',ogImage:'',noindex:false};
const publication=['DRAFT','PUBLISHED','ARCHIVED'];
export const resources:Record<string,Resource>={
 products:{label:'Products',search:['name','sku'],fields:[{key:'name',label:'Name',section:'General'},{key:'slug',label:'Slug'},{key:'sku',label:'SKU'},{key:'shortDescription',label:'Short description',type:'textarea'},{key:'description',label:'Description',type:'textarea'},{key:'care',label:'Care instructions',type:'textarea'},{key:'status',label:'Status',type:'select',options:publication},{key:'images',label:'Gallery (first image is the thumbnail)',type:'json',section:'Media'},{key:'regularPrice',label:'Regular price (PKR)',type:'money',section:'Pricing'},{key:'salePrice',label:'Sale price (PKR)',type:'money',nullable:true},{key:'costPrice',label:'Cost price (PKR)',type:'money',nullable:true},{key:'saleStart',label:'Sale starts',type:'date',nullable:true},{key:'saleEnd',label:'Sale ends',type:'date',nullable:true},{key:'inventory',label:'Simple product inventory',type:'json',section:'Inventory'},{key:'productType',label:'Product type',type:'select',options:['SIMPLE','VARIABLE'],section:'Variants'},{key:'variants',label:'Variants',type:'json'},{key:'categoryIds',label:'Categories',type:'categories',section:'Organization'},{key:'tags',label:'Tags',type:'json'},{key:'featured',label:'Featured',type:'boolean'},{key:'bestseller',label:'Bestseller',type:'boolean'},{key:'newArrival',label:'New arrival',type:'boolean'},{key:'material',label:'Material'},{key:'soleType',label:'Sole type'},{key:'style',label:'Style'},{key:'gender',label:'Gender'},{key:'weight',label:'Weight (kg)',type:'number',nullable:true},{key:'dimensions',label:'Dimensions'},...seo],defaults:{name:'',slug:'',sku:'',shortDescription:'',description:'',care:'',status:'DRAFT',regularPrice:0,salePrice:null,costPrice:null,saleStart:null,saleEnd:null,productType:'SIMPLE',inventory:{quantity:0,lowStock:5,allowBackorders:false,available:true},images:[],variants:[],categoryIds:[],tags:[],featured:false,bestseller:false,newArrival:false,material:'',soleType:'',style:'',gender:'Men',weight:null,dimensions:'',...seoDefaults}},
 categories:{label:'Categories',search:['name','slug'],fields:[{key:'name',label:'Name'},{key:'slug',label:'Slug'},{key:'parentId',label:'Parent category ID',nullable:true,hint:'Leave empty for a root category. IDs appear in the category list.'},{key:'description',label:'Description',type:'textarea'},{key:'image',label:'Image',type:'media'},{key:'banner',label:'Banner',type:'media'},{key:'sortOrder',label:'Sort order',type:'number'},{key:'active',label:'Active',type:'boolean'},...seo],defaults:{name:'',slug:'',parentId:null,description:'',image:'',banner:'',sortOrder:0,active:true,...seoDefaults}},
 inventory:{label:'Inventory',search:[],fields:[{key:'quantity',label:'Stock quantity',type:'number'},{key:'lowStock',label:'Low stock warning',type:'number'},{key:'available',label:'Available',type:'boolean'},{key:'allowBackorders',label:'Allow backorders',type:'boolean'}],defaults:{}},
 orders:{label:'Orders',search:['orderNumber'],fields:[{key:'status',label:'Order status',type:'select',options:['PENDING','CONFIRMED','PROCESSING','SHIPPED','DELIVERED','CANCELLED','RETURNED','REFUNDED']},{key:'paymentStatus',label:'Payment status',type:'select',options:['PENDING','PAID','FAILED','REFUNDED']},{key:'internalNotes',label:'Internal notes',type:'textarea'}],defaults:{}},
 customers:{label:'Customers',search:['name','email','phone'],fields:[],defaults:{},readOnly:true},
 coupons:{label:'Coupons',search:['code'],fields:[{key:'code',label:'Code'},{key:'type',label:'Type',type:'select',options:['PERCENTAGE','FIXED']},{key:'amount',label:'Amount (% or paisa for fixed)',type:'number',hint:'For fixed coupons 100 paisa = PKR 1.'},{key:'minimumOrder',label:'Minimum order (PKR)',type:'money'},{key:'maximumDiscount',label:'Maximum discount (PKR)',type:'money',nullable:true},{key:'startDate',label:'Start date',type:'date',nullable:true},{key:'expiryDate',label:'Expiry',type:'date',nullable:true},{key:'usageLimit',label:'Usage limit',type:'number',nullable:true},{key:'active',label:'Active',type:'boolean'}],defaults:{code:'',type:'PERCENTAGE',amount:10,minimumOrder:0,maximumDiscount:null,startDate:null,expiryDate:null,usageLimit:null,active:true}},
 homepage:{label:'Homepage',search:['title','key'],fields:[{key:'key',label:'Key'},{key:'title',label:'Heading'},{key:'type',label:'Section type',type:'select',options:['HERO','TRUST','HERITAGE','PRODUCTS','CATEGORIES','PROMO','BENEFITS','REVIEWS','WHATSAPP','SEO']},{key:'active',label:'Enabled',type:'boolean'},{key:'sortOrder',label:'Position',type:'number'},{key:'config',label:'Section content and selections',type:'json'}],defaults:{key:'',title:'',type:'PRODUCTS',active:true,sortOrder:0,config:{eyebrow:'',description:'',featured:true,limit:4}}},
 banners:{label:'Banners',search:['title','key'],fields:[{key:'key',label:'Key'},{key:'title',label:'Heading',type:'textarea'},{key:'eyebrow',label:'Eyebrow'},{key:'description',label:'Description',type:'textarea'},{key:'image',label:'Image',type:'media'},{key:'imageAlt',label:'Image alt text'},{key:'buttonLabel',label:'Button label'},{key:'buttonUrl',label:'Button URL'},{key:'active',label:'Active',type:'boolean'}],defaults:{key:'',title:'',eyebrow:'',description:'',image:'',imageAlt:'',buttonLabel:'Shop Now',buttonUrl:'/shop',active:true}},
 reviews:{label:'Reviews',search:['name','content'],fields:[{key:'name',label:'Customer name'},{key:'productId',label:'Product ID (optional)',nullable:true},{key:'rating',label:'Rating (1–5)',type:'number'},{key:'content',label:'Review',type:'textarea'},{key:'source',label:'Source'},{key:'avatar',label:'Avatar',type:'media'},{key:'approved',label:'Approved',type:'boolean'},{key:'featured',label:'Featured',type:'boolean'},{key:'date',label:'Date',type:'date'}],defaults:{name:'',productId:null,rating:5,content:'',source:'Store',avatar:'',approved:false,featured:false,date:new Date().toISOString()}},
 pages:{label:'Pages',search:['title','slug'],fields:[{key:'title',label:'Title'},{key:'slug',label:'Slug'},{key:'content',label:'Content (plain text)',type:'textarea'},{key:'status',label:'Status',type:'select',options:publication},...seo],defaults:{title:'',slug:'',content:'',status:'DRAFT',...seoDefaults}},
 blog:{label:'Blog',search:['title','slug'],fields:[{key:'title',label:'Title'},{key:'slug',label:'Slug'},{key:'excerpt',label:'Excerpt',type:'textarea'},{key:'content',label:'Content (plain text)',type:'textarea'},{key:'image',label:'Featured image',type:'media'},{key:'author',label:'Author'},{key:'category',label:'Category'},{key:'status',label:'Status',type:'select',options:publication},{key:'publishedAt',label:'Publish date',type:'date',nullable:true},...seo],defaults:{title:'',slug:'',excerpt:'',content:'',image:'',author:'',category:'',status:'DRAFT',publishedAt:null,...seoDefaults}},
 navigation:{label:'Navigation',search:['label','url'],fields:[{key:'label',label:'Label'},{key:'url',label:'URL'},{key:'categoryId',label:'Category ID (optional)',nullable:true},{key:'parentId',label:'Parent menu item ID (optional)',nullable:true},{key:'location',label:'Menu',type:'select',options:['MAIN','FOOTER','SOCIAL']},{key:'sortOrder',label:'Order',type:'number'},{key:'visible',label:'Visible',type:'boolean'}],defaults:{label:'',url:'/shop',categoryId:null,parentId:null,location:'MAIN',sortOrder:0,visible:true}},
 media:{label:'Media Library',search:['filename','alt'],fields:[{key:'alt',label:'Alt text'}],defaults:{}},
 settings:{label:'Store Settings',search:[],fields:[{key:'storeName',label:'Store name',section:'Brand'},{key:'logo',label:'Logo',type:'media'},{key:'favicon',label:'Favicon',type:'media'},{key:'description',label:'Footer description',type:'textarea'},{key:'phone',label:'Phone',section:'Contact'},{key:'email',label:'Email'},{key:'whatsapp',label:'WhatsApp (country code and digits)'},{key:'address',label:'Address',type:'textarea'},{key:'facebook',label:'Facebook',section:'Social'},{key:'instagram',label:'Instagram'},{key:'tiktok',label:'TikTok'},{key:'youtube',label:'YouTube'},{key:'currency',label:'Currency',type:'select',options:['PKR'],section:'Shipping'},{key:'freeShipping',label:'Free shipping on every order',type:'boolean'},{key:'shippingFee',label:'Flat shipping fee (PKR)',type:'money'},{key:'freeShippingThreshold',label:'Free shipping threshold (PKR)',type:'money',nullable:true},{key:'announcement',label:'Announcement',section:'Other'},{key:'copyright',label:'Footer copyright'}],defaults:{}},
 users:{label:'Users / Admins',search:['name','email'],fields:[{key:'name',label:'Name'},{key:'email',label:'Email'},{key:'password',label:'Password (12+ characters; blank keeps current)',type:'password'},{key:'role',label:'Role',type:'select',options:['SUPER_ADMIN','ADMIN','EDITOR','ORDER_MANAGER']},{key:'active',label:'Active',type:'boolean'}],defaults:{name:'',email:'',password:'',role:'EDITOR',active:true}}
};
