"use client";
import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { resources } from '@/lib/admin-resources';
import { MediaPicker } from './media-picker';
import { JsonFields,type JsonValue } from './json-fields';
type Choice={id:string;name:string;parentId?:string|null};
const sectionTemplates:Record<string,Record<string,JsonValue>>={HERO:{bannerKey:'hero'},PROMO:{bannerKey:'promo'},TRUST:{items:[]},HERITAGE:{description:''},PRODUCTS:{eyebrow:'',description:'',productIds:[],categorySlug:'',featured:false,limit:4},CATEGORIES:{eyebrow:'',categoryIds:[]},BENEFITS:{description:'',image:'',items:[]},REVIEWS:{eyebrow:'',reviewIds:[],limit:12},WHATSAPP:{description:'',buttonLabel:'Order on WhatsApp'},SEO:{blocks:[]}};
export function Editor({resource,id,initial,categories=[]}:{resource:string;id?:string;initial:Record<string,unknown>;categories?:Choice[]}){
 const config=resources[resource];const [data,setData]=useState<Record<string,unknown>>({...config.defaults,...initial});const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [issues,setIssues]=useState<{path:string;message:string}[]>([]);const router=useRouter();
 function change(key:string,value:unknown){setData(old=>{const next={...old,[key]:value};if(!id&&['name','title'].includes(key)&&!old.slug)next.slug=String(value).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');if(resource==='homepage'&&key==='type')next.config=sectionTemplates[String(value)]||{};return next;});}
 return <form className="admin-form space-y-5" onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');setIssues([]);try{const body=Object.fromEntries(config.fields.map(f=>[f.key,data[f.key]??(f.nullable?null:'')]));if(resource==='homepage'){const c=body.config as Record<string,unknown>;if(c.categorySlug==='')delete c.categorySlug;}
 const r=await fetch('/api/admin/'+resource+(id?'/'+id:''),{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok){setIssues(result.issues||[]);throw Error(result.error);}setMessage('Saved successfully');if(!id&&result.id){router.replace('/admin/'+resource+'/'+result.id);}router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Could not save');}finally{setBusy(false);}}}>
 {config.fields.map(field=><div key={field.key}>{field.section&&<h2 className="mb-5 mt-8 border-b pb-3 text-xl font-bold">{field.section}</h2>}<div className="rounded-lg border bg-surface p-4"><label htmlFor={field.key} className="mb-2 block text-sm font-semibold">{field.label}</label>{field.type==='media'?<MediaPicker value={String(data[field.key]||'')} onChange={value=>change(field.key,value)}/>:field.type==='json'?<JsonFields value={data[field.key] as JsonValue} name={field.key} onChange={value=>change(field.key,value)}/>:field.type==='categories'?<div className="grid gap-2 sm:grid-cols-2">{categories.map(c=><label key={c.id} className="flex gap-2 text-sm"><input type="checkbox" checked={(data[field.key] as string[]||[]).includes(c.id)} onChange={e=>{const current=data[field.key] as string[]||[];change(field.key,e.target.checked?[...current,c.id]:current.filter(id=>id!==c.id));}}/>{c.parentId?'↳ ':''}{c.name}</label>)}</div>:field.key==='parentId'&&resource==='categories'?<select id={field.key} value={String(data[field.key]||'')} onChange={e=>change(field.key,e.target.value||null)}><option value="">Root category</option>{categories.filter(c=>c.id!==id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>:field.type==='boolean'?<input id={field.key} type="checkbox" checked={Boolean(data[field.key])} onChange={e=>change(field.key,e.target.checked)}/>:field.type==='select'?<select id={field.key} value={String(data[field.key]||'')} onChange={e=>change(field.key,e.target.value)}>{field.options?.map(option=><option key={option}>{option}</option>)}</select>:field.type==='textarea'?<textarea id={field.key} rows={field.key==='content'?12:4} value={String(data[field.key]||'')} onChange={e=>change(field.key,e.target.value)}/>:<input id={field.key} type={field.type==='date'?'datetime-local':field.type==='money'||field.type==='number'?'number':field.type==='password'?'password':'text'} step={field.type==='money'?'0.01':undefined} value={data[field.key]==null?'':field.type==='money'?Number(data[field.key])/100:field.type==='date'?String(data[field.key]).slice(0,16):String(data[field.key])} onChange={e=>change(field.key,e.target.value===''&&field.nullable?null:field.type==='money'?Math.round(Number(e.target.value)*100):field.type==='number'?Number(e.target.value):field.type==='date'?(e.target.value?new Date(e.target.value).toISOString():null):e.target.value)}/>} {field.hint&&<p className="mt-2 text-xs text-[#777]">{field.hint}</p>}{issues.filter(i=>i.path===field.key||i.path.startsWith(field.key+'.')).map((i,index)=><p key={index} className="mt-2 text-sm text-red-700">{i.path}: {i.message}</p>)}</div></div>)}
 <div className="sticky bottom-0 flex flex-wrap items-center gap-4 rounded border bg-surface p-4 shadow-sm"><button disabled={busy} className="rounded bg-brand px-6 py-3 font-bold disabled:opacity-50">{busy?'Saving…':'Save changes'}</button><Link href={'/admin/'+resource} className="text-sm underline">Back to list</Link>{message&&<p role="status" className={message==='Saved successfully'?'text-green-700':'text-red-700'}>{message}</p>}</div></form>;
}
