import EmbeddedPostgres from 'embedded-postgres';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
process.loadEnvFile('.env');
const url=new URL(process.env.DATABASE_URL);
if(url.hostname!=='127.0.0.1'||url.port!=='54329')throw Error('Local helper only starts 127.0.0.1:54329. Use your external database directly.');
const databaseDir=resolve('.local-postgres');
const pg=new EmbeddedPostgres({databaseDir,user:decodeURIComponent(url.username),password:decodeURIComponent(url.password),port:54329,persistent:true,initdbFlags:['--encoding=UTF8','--locale=C'],postgresFlags:['-h','127.0.0.1'],onLog:()=>{},onError:message=>console.error(String(message))});
if(!existsSync(resolve(databaseDir,'PG_VERSION')))await pg.initialise();
await pg.start();
const client=pg.getPgClient();await client.connect();
const name=url.pathname.slice(1);
if(!/^[a-z0-9_]+$/.test(name))throw Error('Invalid local database name');
const result=await client.query('SELECT 1 FROM pg_database WHERE datname=$1',[name]);
if(!result.rowCount)await pg.createDatabase(name);
await client.end();
console.log('Zarshal PostgreSQL ready on 127.0.0.1:54329. Keep this process running.');
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,async()=>{await pg.stop();process.exit(0);});
setInterval(()=>{},60000);
