import {writeFileSync,unlinkSync} from 'node:fs';
writeFileSync('components/header.tsx',`"use client";
import Image from 'next/image';
import Link from 'next/link';
import { Menu,Search,ShoppingBag,User } from 'lucide-react';
import { useState } from 'react';
import { StoreNavigation } from './store-navigation';
import { useCart } from './cart-provider';
import type { StoreSettings } from '@/lib/validation';
import type { MenuItem } from '@/lib/navigation-types';
export function Header({settings,items}:{settings:StoreSettings;items:MenuItem[]}){
 const [mobileOpen,setMobileOpen]=useState(false);const [searchOpen,setSearchOpen]=useState(false);const {items:cart}=useCart();
 return <header className="sticky top-0 z-40 bg-white shadow-[0_1px_0_rgba(0,0,0,0.04)]"><div className="container-shell flex h-[72px] items-center justify-between gap-4"><div className="flex items-center gap-4"><button type="button" className="inline-flex h-9 w-9 items-center justify-center rounded-[3px] border border-[#e7e7e7] lg:hidden" aria-label="Open menu" onClick={()=>setMobileOpen(true)}><Menu className="h-4 w-4"/></button><Link href="/" aria-label={settings.storeName+' home'}><Image src={settings.logo} alt={settings.storeName} width={150} height={50} className="h-auto w-[120px] sm:w-[150px]"/></Link></div><nav aria-label="Main navigation" className="hidden flex-1 justify-center lg:flex"><StoreNavigation items={items}/></nav><div className="flex items-center gap-2 sm:gap-3"><button className="flex h-9 w-9 items-center justify-center rounded-[3px] border border-[#e7e7e7]" aria-label="Search" aria-expanded={searchOpen} onClick={()=>setSearchOpen(!searchOpen)}><Search className="h-4 w-4"/></button><Link href="/admin" className="hidden h-9 w-9 items-center justify-center rounded-[3px] border border-[#e7e7e7] sm:flex" aria-label="Store administration"><User className="h-4 w-4"/></Link><Link href="/cart" className="relative flex h-9 w-9 items-center justify-center rounded-[3px] border border-[#e7e7e7]" aria-label="Cart"><ShoppingBag className="h-4 w-4"/><span className="absolute -right-1 -top-1 flex h-4 min-w-4 items-center justify-center rounded-full bg-[#f9bf00] px-1 text-[9px] font-bold">{cart.reduce((n,i)=>n+i.quantity,0)}</span></Link></div></div>{searchOpen&&<form action="/shop" className="container-shell flex gap-2 pb-4"><input name="q" aria-label="Search products" placeholder="Search products" className="flex-1 border p-2"/><button className="bg-[#f9bf00] px-4">Search</button></form>}{mobileOpen&&<div className="fixed inset-0 z-50" role="dialog" aria-modal="true" aria-label="Navigation"><button className="absolute inset-0 bg-black/25" aria-label="Close menu" onClick={()=>setMobileOpen(false)}/><aside className="absolute left-0 top-0 h-full w-[86%] max-w-sm overflow-y-auto bg-white p-5 shadow-lg"><div className="mb-6 flex justify-between"><span className="text-xl font-black uppercase">{settings.storeName}</span><button aria-label="Close menu" onClick={()=>setMobileOpen(false)}>×</button></div><nav><StoreNavigation items={items} mobile onNavigate={()=>setMobileOpen(false)}/></nav></aside></div>}</header>;
}
`);
writeFileSync('components/footer.tsx',`import Image from 'next/image';
import Link from 'next/link';
import { MapPin,Phone,ShoppingBag } from 'lucide-react';
import type { StoreSettings } from '@/lib/validation';
import type { MenuItem } from '@/lib/navigation-types';
import type { Category } from '@prisma/client';
export function Footer({settings,items,categories}:{settings:StoreSettings;items:MenuItem[];categories:Category[]}){return <footer className="bg-white"><div className="container-shell py-12"><div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4"><div><Link href="/"><Image src={settings.logo} alt={settings.storeName} width={150} height={50} className="h-auto w-[150px]"/></Link><p className="mt-4 max-w-xs text-[13px] leading-6 text-[#666666]">{settings.description}</p><div className="mt-5 flex flex-wrap gap-3 text-sm">{(['facebook','instagram','tiktok','youtube'] as const).map(key=>settings[key]?<a key={key} href={settings[key]} className="capitalize">{key}</a>:null)}</div></div><div><h4 className="text-[12px] font-bold uppercase tracking-[0.12em]">Shop by Categories</h4><ul className="mt-4 space-y-3 text-[13px] text-[#666]">{categories.map(c=><li key={c.id}><Link href={'/category/'+c.slug}>{c.name}</Link></li>)}</ul></div><div><h4 className="text-[12px] font-bold uppercase tracking-[0.12em]">Useful Links</h4><ul className="mt-4 space-y-3 text-[13px] text-[#666]">{items.map(i=><li key={i.id}><Link href={i.url}>{i.label}</Link></li>)}</ul></div><div><h4 className="text-[12px] font-bold uppercase tracking-[0.12em]">Contact Info</h4><ul className="mt-4 space-y-3 text-[13px] text-[#666]"><li className="flex items-center gap-2"><Phone className="h-4 w-4"/><a href={'tel:'+settings.phone.replace(/[^+0-9]/g,'')}>{settings.phone}</a></li><li className="flex items-center gap-2"><MapPin className="h-4 w-4"/>{settings.address}</li>{settings.email&&<li><a href={'mailto:'+settings.email}>{settings.email}</a></li>}<li className="flex items-center gap-2"><ShoppingBag className="h-4 w-4"/>Online store for heritage essentials</li></ul></div></div><div className="mt-10 border-t border-[#e7e7e7] pt-5 text-[12px] text-[#666]">{settings.copyright}</div></div></footer>;}
`);
writeFileSync('components/product-grid.tsx',`import Image from 'next/image';
import Link from 'next/link';
import type { ProductCard } from '@/lib/products';
import { money } from '@/lib/pricing';
export function ProductGrid({products}:{products:ProductCard[]}){if(!products.length)return <p className="py-8 text-sm text-[#666]">No products match your selection.</p>;return <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{products.map(p=><article key={p.id} className="rounded-[4px] border border-[#e7e7e7] bg-white p-3"><Link href={'/product/'+p.slug} className="relative block overflow-hidden rounded-[3px] bg-[#f7f7f7]"><div className="relative aspect-square">{p.image&&<Image src={p.image} alt={p.imageAlt} fill sizes="(min-width: 1280px) 25vw, (min-width: 768px) 50vw, 100vw" className="object-cover"/>}</div>{(p.percentage>0||p.badge)&&<span className="absolute left-3 top-3 rounded-[2px] bg-[#f9bf00] px-2 py-1 text-[10px] font-semibold uppercase">{p.percentage>0?'-'+p.percentage+'%':p.badge}</span>}</Link><div className="mt-4"><div className="text-[11px] font-semibold uppercase tracking-[0.08em] text-[#8e8e8e]">Handmade</div><h3 className="mt-2 text-[14px] font-semibold leading-5"><Link href={'/product/'+p.slug}>{p.name}</Link></h3><div className="mt-3 flex items-center gap-2 text-[11px] text-[#666]">{p.current<p.regular&&<span className="line-through">{money(p.regular)}</span>}<span className="text-[13px] font-bold text-[#1f1f1f]">{money(p.current)}</span></div><Link href={'/product/'+p.slug} className="mt-4 block w-full border border-[#1f1f1f] bg-[#f9bf00] px-3 py-2 text-center text-[11px] font-bold uppercase tracking-[0.12em] transition hover:bg-[#e5ad00]">{p.available?'Select Options':'Out of Stock'}</Link></div></article>)}</div>;}
`);
writeFileSync('components/seo-content.tsx',`export function SeoContent({blocks}:{blocks:{title:string;content:string}[]}){return <section className="bg-white"><div className="container-shell py-12 lg:py-16"><div className="space-y-5 text-[13px] leading-7 text-[#666666]">{blocks.map((block,index)=><div key={index} className="space-y-5"><h3 className="text-[16px] font-bold uppercase tracking-[0.02em] text-[#1f1f1f]">{block.title}</h3><p className="whitespace-pre-line">{block.content}</p></div>)}</div></div></section>;}
`);
// Replaced by the store route group; no duplicate homepage route.
unlinkSync('app/page.tsx');
// Navigation now uses a shared database-fed recursive menu.
writeFileSync('components/desktop-nav.tsx',`export { StoreNavigation as DesktopNav } from './store-navigation';\n`);
writeFileSync('components/mobile-nav.tsx',`export { StoreNavigation as MobileNav } from './store-navigation';\n`);
